<?php
// It's just a region for testing out code templates.
require_once('../../sirel.php');
//------------------------------------------------------------------------



class Blackboard {




// RENESSAATOR_BLOCK_START
// RENESSAATOR_BLOCK_ID=block1
// RENESSAATOR_SOURCE_LANGUAGE=Ruby
// RENESSAATOR_SOURCE_START
// SIREL_CODE_GENERATION="/home/zornilemma/Projektid/progremise_infrastruktuur/teeke/sirel/sirel/src/dev_tools/code_generation/"
// require(SIREL_CODE_GENERATION+"/sirel_cg1.rb")
// #require(SIREL_CODE_GENERATION+"/by_file/blackboard_block1.rb")
// RENESSAATOR_SOURCE_END
//
// RENESSAATOR_AUTOGENERATED_TEXT_START

// RENESSAATOR_AUTOGENERATED_TEXT_END
// RENESSAATOR_BLOCK_END

}// class Blackboard

$s="[\\\"iii\\\"]";
echo $s;

$s0=mb_ereg_replace('[\\\\]"', '"', $s);
$s1=mb_ereg_replace('[\\r]', "", $s0);
echo '<br/>'.$s1;



//$bb->run();
//------------------------------------------------------------------------
?>
